#!@bash@/bin/bash
export PATH="@ckiePath@"
set -euo pipefail

# Upload a file to i.ckie.dev (bokkusu)
tfn="$(tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c 7).''${1##*.}"
rsync "$1" bokkusu:/var/lib/rtc-files/ckiedev/"$tfn"
echo https://i.ckie.dev/"$tfn"
echo https://i.ckie.dev/"$tfn" | xclip -selection c
