#!@bash@/bin/bash
export PATH="@ckiePath@"
set -euo pipefail

if (( $# != 1 )) then
   >&2 echo "usage: prism-symlink <prism-profile-name>"
   exit 1
fi

profile="$HOME/.local/share/PrismLauncher/instances/$1/.minecraft"

rm -vrf "$profile"/screenshots

ln -s ~/.minecraft/screenshots "$profile/"
ln -s ~/.minecraft/resourcepacks "$profile/"
ln -s ~/.minecraft/logs "$profile/"
cp ~/.minecraft/option*.txt "$profile/"
