#!@bash@/bin/bash
export PATH="@ckiePath@"
set -euo pipefail

if (( $# != 1 )) then
   >&2 echo "usage: prism-symlink <prism-profile-name>"
   exit 1
fi

profile="$HOME/.local/share/PrismLauncher/instances/$1/.minecraft"

rmdir "$profile"/{screenshots,resourcepacks} >/dev/null 2>&1 || true

ln -s ~/.minecraft/screenshots "$profile/"
ln -s ~/.minecraft/resourcepacks "$profile/"
ln -s ~/.minecraft/logs "$profile/"
