# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  sources = import ../../nix/sources.nix;
  inherit (sources) nixos-hardware;
in {
  imports = [
    "${nixos-hardware}/common/pc/ssd"
    "${nixos-hardware}/common/cpu/amd"
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.rtl8821au ];
  boot.extraModprobeConfig = ''
    # Enable VHT and USB3 support
    # VHT is a part of 802.11ax
    options 8821au rtw_vht_enable=2 rtw_switch_usb_mode=1
  '';

  boot.initrd.luks.devices."btrfs".device =
    "/dev/disk/by-uuid/4800352d-e038-404e-a122-df7e87419cf1";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/91df680e-8038-435c-bf23-db8e9d0ade85";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C81C-0938";
    fsType = "vfat";
  };

  fileSystems."/mnt/games" = {
    device = "/dev/md127";
    fsType = "ext4";
  };

  fileSystems."/mnt/backup" = {
    device = "/dev/disk/by-uuid/08f2ac6c-3564-4110-a436-fed882a9f4e8";
    fsType = "ext4";
  };

  swapDevices = [{ device = "/nix/swap"; }];

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
