# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  sources = import ../../nix/sources.nix;
  inherit (sources) nixos-hardware;
in {
  imports = [
    "${nixos-hardware}/common/pc/ssd"
    "${nixos-hardware}/common/cpu/amd"
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "ddcci" # ext. monitor (144hz, LG) brightness control, flimsy..
    "nct6775" # amd cpu temp monitor on this motherboard (msi B450M gaming plus)
  ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    rtl8821au
    ddcci-driver
  ];
  boot.extraModprobeConfig = ''
    # Enable VHT and USB3 support
    # VHT is a part of 802.11ax
    options 8821au rtw_vht_enable=2 rtw_switch_usb_mode=1
  '';

  # FIXME: These Ryzen 5 3600 cores are just Dead after some years.
  # Inexplicably, dead. Sometimes cpu0 is also dead, but we can't disable it.
  # system.activationScripts.offlineRyzenCores =
  #   "for x in /sys/devices/system/cpu/cpu{3,10,4,9}/online; do echo 0 > $x; done";
  # system.activationScripts.offlineGoodRyzenCores =
  #   "for x in /sys/devices/system/cpu/cpu{1,2,5,6,7,8,11}/online; do echo 0 > $x; done";

  # systemd.services.display-manager.serviceConfig.CPUAffinity = "1,2,5,6,7,8,11";

  boot.initrd.luks.devices."nvmecrypt".device =
    "/dev/disk/by-uuid/491bf5ed-1d5d-48e6-a048-c692ade24d40";

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1CFB-B38F";
    fsType = "vfat";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/130c6ff5-fd55-4843-82fc-220729c64842";
    fsType = "ext4";
    # give an hour to unlock before timing out and
    # entering emergency mode, due to systemd flaws. (even if we do: systemctl default)
    #
    # https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$8xMdHFvulZ7LgR2SnOwMlCoqd9BdsZGLD4RdajISVWI?via=nixos.org&via=matrix.org&via=nixos.dev
    options = [ "x-systemd.device-timeout=3600" ];
  };

  # blows things up, I think.
  # swapDevices =
  #   [{ device = "/dev/disk/by-uuid/a5b85a35-f98c-4616-bc75-e511001ad05d"; }];

  fileSystems."/mnt/games" = {
    device = "/dev/md127";
    fsType = "ext4";
  };

  fileSystems."/mnt/backup" = {
    device = "/dev/disk/by-uuid/08f2ac6c-3564-4110-a436-fed882a9f4e8";
    fsType = "ext4";
  };

  hardware.cpu.amd.updateMicrocode = true;
}
