# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ehci_pci" "ahci" "ata_piix" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2182ff14-faa1-4ec7-b9a7-03ae63690baa";
    fsType = "ext4";
    options = [ "x-systemd.device-timeout=3600" ];
  };

  boot.initrd.luks.devices."root".device =
    "/dev/disk/by-uuid/b28c8276-5d34-4dfd-a62f-94d63327b93a";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/649A-B53C";
    fsType = "vfat";
  };

  swapDevices = [ ];

}
