[hosts.cookiemonster]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0wKpIYHIg12GBvnwDaFGrsTNYgl6VPdJ/x2Z7FkMXf"
mac_address = "50:3e:aa:05:2a:90"
syncthing_id = "MVCZQ2L-XCK3Y2Z-R7Q2UT6-TZK6CVH-WUN6TFH-I3ZOCRS-OLZAN7C-XZ4BHAF"
[hosts.bokkusu]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFjcN4YgKxeaeQEERpYIwwZJXV3Hre4FfrD+cNi69Z6A"
[hosts.thonkcookie]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAAC83UXW5rtEPlEqDT5c/W0DTFFwsVah6ZlCg1FO9kr"
syncthing_id = "IE7OX5L-IH67GHS-5DDDGDY-TYHLYED-G44LTPX-YWQEQQK-6AX6OYJ-SRRWMA7"
[hosts.aquamarine]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILMVvufwH76hYDhvXGu071XExCQFv0uZjwNaBn/WBbk8"
[hosts.drapion]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ2azaroNAPS5GtjAqf6PdVAqEW7MgghYxlxKy+VgTH6"
[hosts.pookieix]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBacSyNUF7XfWbo4nUuG0DLha+cHReyCm2zeBZcRaYLy"
