#+TITLE: Config
#+PROPERTY: header-args :tangle yes :cache yes :results silent :padline no
* Basics
** whoami
#+BEGIN_SRC elisp
(setq user-full-name "ckie"
      user-mail-address "us@ckie.dev")
#+END_SRC
** display
*** theme
Sometimes I also use =doom-laserwave=.
#+BEGIN_SRC elisp
(setq doom-theme 'doom-sourcerer-cookie)
#+END_SRC
*** font
The variable pitch font is a nice change from a screen full of monospace text (:
#+BEGIN_SRC elisp
(setq doom-font (font-spec :family "JetBrains Mono" :size 13)
      doom-variable-pitch-font (font-spec :family "Inter" :size 16))
#+END_SRC
=SPC t b= makes everything too big:
#+BEGIN_SRC elisp
(setq doom-big-font-increment 3)
#+END_SRC
*** lines / chars
This makes line numbers count up/down from the current line instead of from the beginning of the buffer.
#+BEGIN_SRC elisp
(setq display-line-numbers-type 'relative)
#+END_SRC
This keeps 8 lines of extra content on the top and bottom when scrolling a buffer.
#+BEGIN_SRC elisp
(setq scroll-margin 8)
#+END_SRC
This strikes a nice balance between taking up a nice amount of the screen and still being readable.
#+BEGIN_SRC elisp
(setq-default fill-column 100)
#+END_SRC
*** line wrapping before window end
#+BEGIN_SRC elisp :tangle packages.el
(package! visual-fill-column)
#+END_SRC
*** client window transparency
~alpha-background~ requires emacs 28, ~alpha~ does not
#+BEGIN_SRC elisp
(add-to-list 'default-frame-alist '(alpha-background . 0))
#+END_SRC
*** suppress messages
#+BEGIN_SRC elisp
(defun ckie--suppress-messages (func &rest args)
  "Suppress message output from FUNC."
  ;; Some packages are too noisy.
  ;; https://superuser.com/questions/669701/emacs-disable-some-minibuffer-messages
  (cl-flet ((silence (&rest args1) (ignore)))
    (advice-add 'message :around #'silence)
    (unwind-protect
        (apply func args)
      (advice-remove 'message #'silence))))

;; Suppress "Cleaning up the recentf...done (0 removed)"
(advice-add 'recentf-cleanup :around #'ckie--suppress-messages)
#+END_SRC
*** thinner modeline
The default doom-modeline takes up a few too many vertical pixels. Let's have less padding.
#+BEGIN_SRC elisp
(after! doom-modeline
  (setq doom-modeline-height (+ (doom-modeline--font-height) 2)))
#+END_SRC
Note =doom-modeline-height= is only used in GUI.
* Doom/Extras
** fix config edit keybind
Doom Emacs assumes your config will be in =~/.doom=, but mine isn't!
#+BEGIN_SRC elisp
(map! :leader "f P" (cmd! (doom-project-browse "~/git/nixfiles/modules/doom-emacs/config/")))
#+END_SRC
** count buffers
I like counting buffers. This is probably from StackOverflow
#+BEGIN_SRC elisp
(defun ckie-count-buffers (&optional display-anyway)
  "Display or return the number of buffers."
  (interactive)
  (let ((buf-count (length (buffer-list))))
    (if (or (interactive-p) display-anyway)
        (message "%d buffers in this Emacs" buf-count)) buf-count))
(map! :leader "b c" #'ckie-count-buffers)
#+END_SRC
** mu4e/email
mu4e occasionally messes up its database without this, see [[https://github.com/djcb/mu/issues/2055][djcb/mu#2055]].
#+BEGIN_SRC elisp
(after! mu4e (setq mu4e-index-lazy-check '()))
#+END_SRC
#+BEGIN_SRC elisp :tangle packages.el
(package! mu4e-views)
#+END_SRC
***  hide redundant modeline thingy
#+BEGIN_SRC elisp
(after! doom-modeline (setq doom-modeline-mu4e nil))
#+END_SRC
*** use home-manager email configuration
see [[=/modules/mail-client.nix]]= (TODO figure out how to link relative paths properly)
#+BEGIN_SRC elisp
(after! mu4e
  (setq sendmail-program (executable-find "msmtp")
        send-mail-function #'smtpmail-send-it
        message-sendmail-f-is-evil t
        message-sendmail-extra-arguments '("--read-envelope-from")
        message-send-mail-function #'message-send-mail-with-sendmail))
#+END_SRC
*** set date/time format
#+BEGIN_SRC elisp
(setq mu4e-headers-date-format "%d/%m/%y")
(setq mu4e-headers-time-format "%d/%m/%y %l:%M:%S %p")
#+END_SRC
*** Unoverride: Ctrl - is text scale, not mu4e related
#+BEGIN_SRC elisp
(after! mu4e
  (map! :map mu4e-view-mode-map :n "C--" #'text-scale-decrease))
#+END_SRC
*** disable badly-performing smartparens-mode in compose view
#+BEGIN_SRC elisp
(after! mu4e
    (add-hook 'mu4e-compose-mode-hook (lambda () (smartparens-mode 0))))
#+END_SRC
*** set sent dir to use ckiedev
this actually makes no sense, FIXME, because gmail/non-ckiedev messages may also be sent from emacs, and then be put into ckiedev's Sent dir but in practice i hope this doesn't happen
#+BEGIN_SRC elisp
(after! mu4e
    (setq mu4e-sent-folder "/ckiedev/Sent"))
#+END_SRC
** org-mode
=Sync= gets synced between devices, so it is a good place for this.
#+BEGIN_SRC elisp
(setq org-directory "~/Sync/org/")
(add-hook 'org-mode-hook #'writeroom-mode)
(add-hook 'org-mode-hook #'hl-todo-mode)
#+END_SRC
writeroom hijacks the row length
#+BEGIN_SRC elisp
(setq writeroom-width 70)
#+END_SRC
#+BEGIN_QUOTE
To save the clock history across Emacs sessions, use:
#+END_QUOTE
[[https://orgmode.org/manual/Clocking-Work-Time.html][~ src ~]]
#+BEGIN_SRC elisp
(setq org-clock-persist 'history)
(org-clock-persistence-insinuate)
#+END_SRC
** adoc-mode
#+BEGIN_SRC elisp :tangle packages.el
(package! adoc-mode)
#+END_SRC
** mcf-mode
minecraft syntax highlighting, defined in =nixfiles/modules/doom-emacs.nix=
#+BEGIN_SRC elisp :tangle packages.el
;; (package! mcf-mode)
#+END_SRC
** discord
discord intergration, manually enabled when I feel like it
#+BEGIN_SRC elisp :tangle packages.el
(package! elcord)
#+END_SRC
** svelte
For =.svelte= files
#+BEGIN_SRC elisp :tangle packages.el
(package! svelte-mode)
#+END_SRC
** platformio
#+BEGIN_SRC elisp :tangle packages.el
(package! platformio-mode)
#+END_SRC
** lua LSP
the lua LSP mode is annoying and searches for some specific path =~/.config= we don't have!
#+BEGIN_SRC elisp
(setq lsp-clients-lua-language-server-bin "lua-language-server")
#+END_SRC
** brightscript-mode.el
its just copy pasted in here. not touching NDE rn.
#+BEGIN_SRC elisp
(add-load-path! "vendor")
(require 'brightscript-mode)
(add-to-list 'auto-mode-alist '("\\.brs\\'" . brightscript-mode))
; pretend we also know BrighterScript
(add-to-list 'auto-mode-alist '("\\.bs\\'" . brightscript-mode))
#+END_SRC
** vertico ~ to home keybind
#+BEGIN_SRC elisp
(defun ckie--vertico-go-to-home ()
  "Navigate vertico to the user's home directory"
  (interactive)
  (beginning-of-line)
  (let ((pt (point))) (end-of-line) (delete-region pt (point)))
  (insert "~/"))
; broken because of https://github.com/minad/vertico/issues/214
(after! vertico (map! :map vertico-map "~" #'ckie--vertico-go-to-home))
#+END_SRC
** projectile autoknown
#+BEGIN_SRC elisp
(defun ckie-refresh-projectile-known-list ()
  (interactive)
  "Adds all directories from ~/git to projectile-known-projects"
  (setq projectile-known-projects
        (-distinct (append
                    projectile-known-projects
                    (--filter (f-directory? it) (mapcar (lambda (x) (format "~/git/%s/" x))
                                                        (nthcdr 2 (directory-files "~/git"))))))))
(after! projectile
  (advice-add 'projectile-switch-project :before #'ckie-refresh-projectile-known-list))
#+END_SRC
** nixpkgs workspace uses nixpkgs-fmt
#+BEGIN_SRC elisp
(advice-add '+workspace-switch
            :around (lambda
                      (orig-fn &rest r)
                      (setq nix-nixfmt-bin (if (string= (car r) "nixpkgs") "nixpkgs-fmt" "nixfmt"))
                      (apply orig-fn r)))

(after! format-all (define-format-all-formatter nixfmt
    (:executable "nixfmt")
    (:install "nix-env -f https://github.com/serokell/nixfmt/archive/master.tar.gz -i")
    (:modes nix-mode)
    (:format (format-all--buffer-easy (if (string= (+workspace-current-name) "nixpkgs") "nixpkgs-fmt" "nixfmt")))))
#+END_SRC
** force PageUp/PageDn to scroll in vertico
#+BEGIN_SRC elisp
(after! vertico (map!
    :map vertico-map
        :g "<prior>" 'vertico-scroll-down
        :g "<next>" 'vertico-scroll-up))
#+END_SRC
** advice: unadvice
[[https://emacs.stackexchange.com/questions/24657/unadvise-a-function-remove-all-advice-from-it#24658][StackOverflow]]
#+BEGIN_SRC elisp
(defun ckie-advice-unadvice (sym)
  "Remove all advices from symbol SYM."
  (interactive "aFunction symbol: ")
  (advice-mapc (lambda (advice _props) (advice-remove sym advice)) sym))
(map! :leader :n "h d k" #'ckie-advice-unadvice)
#+END_SRC
** projectile init state
#+BEGIN_SRC elisp
(defun ckie-startup-init-state ()
  "Initalize Emacs state to satisfy the Cookie"
  (interactive)
  (advice-remove 'projectile-switch-project #'ckie-refresh-projectile-known-list)
  (setq +workspaces-switch-project-function #'find-file)
  (f-touch (concat doom-cache-dir (f-path-separator) ".projectile"))
  (dolist (name `("~/Sync/" "~/git/nixfiles/" "~/git/nixpkgs/" ,doom-cache-dir))
    (+workspace/new)
    (projectile-switch-project-by-name name))
  (=mu4e) ; *mu4e* workspace, it eats the current workspace so we opened a dummy one.
  (+workspace/delete "main")
  (setq +workspaces-switch-project-function #'doom-project-find-file)
  (advice-add 'projectile-switch-project :before #'ckie-refresh-projectile-known-list))

(map! :leader :n "q k" #'ckie-startup-init-state)
; (add-hook 'after-init-hook #'ckie-startup-init-state) ;runs too early
#+END_SRC
** verb (HTTP requests meet org mode)
#+BEGIN_SRC elisp :tangle packages.el
(package! verb)
#+END_SRC
** unfuck doom themes
#+BEGIN_SRC elisp
(advice-add 'consult-theme :after (lambda (&rest r)
                                     (setq doom-theme nil)))
#+END_SRC
** chocolate doom
#+BEGIN_SRC elisp
(add-hook 'c-mode-hook (lambda ()
  (when (and buffer-file-name
             (or (-any? (lambda (x) (string-match x buffer-file-name)) '("chocolate-doom" "crispy-doom")))
    (c-set-style "bsd")
    (setq indent-tabs-mode nil)
    (setq tab-width 8)
    (setq c-basic-offset 4)))))
#+END_SRC
** flycheck improvements
*** add keybind for listing errors (in a minibuf)
#+BEGIN_SRC elisp
(map! :leader "c X" #'flycheck-list-errors)
#+END_SRC
*** enable popup tips for rust
#+BEGIN_SRC elisp
(add-hook 'rust-mode-hook 'flycheck-popup-tip-mode)
#+END_SRC
** magit
*** add some binds
**** =SPC g o y= for copying the VCS url
#+BEGIN_SRC elisp
(map! :leader "g o y" #'bar-to-clipboard)
#+END_SRC
**** =SPC g c v= for instant commit fixup
#+BEGIN_SRC elisp
(map! :leader "g c v" #'magit-commit-instant-fixup)
#+END_SRC
*** don't graph in the log by default, it's slow as heck
#+BEGIN_SRC elisp
(put 'magit-log-mode 'magit-log-default-arguments '("-n512" "--decorate"))
#+END_SRC


** emmet keybind DWIM on tab
#+BEGIN_SRC elisp
(map! :mode emmet-mode :i "TAB" #'+web/indent-or-yas-or-emmet-expand)
#+END_SRC

** talon integration
*** display  filename exclusively in window title
as per [[https://github.com/knausj85/knausj_talon/blob/4243b257fb0294b73d03b4308f6a46f5bbdded2b/apps/emacs/emacs.py#L345-L351][this]]
#+BEGIN_SRC elisp
(setq-default frame-title-format '((:eval (buffer-name (window-buffer (minibuffer-selected-window))))))
#+END_SRC
